title: Resume
description: Resume is a Grav adaptation of Fernando Báez resume PSD theme.
author:
  name: Team Grav
  email: 'joe@test.com'
metadata:
    description: 'Resume is a free and responsive theme for **Grav**. Its a port of Resume template by HTML5UP.'

website: "justcreativeideas.com"

address:
    - line: "C/ Magallanes 21, 7ºF"
    - line: "28015,"
    - line: "Madrid. SPAIN."
contact: 
    - line: "fernando@justcreativeideas.com"
    - line: "+34 650 39 25 19"
    - line: "@fernandobaez88"

# Main Menu
menu:
  - text: External link
    description: "External link with description."
    link: "#" 

social:
  - text: Twitter
    url: http://twitter.com/getgrav
  - text: Facebook
    url: http://facebook.com
  - text: Google
    url: http://plus.google.com
  - text: Github
    url: https://github.com/getgrav/grav
