title: Resume
description: Free and responsive theme for GRAV. Port of Resume template by Wordpress.org.
author:
  name: Team Grav
  email: 'joe@test.com'
metadata:
    description: 'Resume is a free and responsive theme for **Grav**. Its a port of Resume template by HTML5UP.'

# Main Menu
menu:
  - text: External link
    description: "External link with description."
    link: "#" 

social:
  - text: Twitter
    url: http://twitter.com/getgrav
  - text: Facebook
    url: http://facebook.com
  - text: Google
    url: http://plus.google.com
  - text: Github
    url: https://github.com/getgrav/grav
